instapjt/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:pk>/profile/", views.profile, name="profile"),
    path('<int:pk>/follow', views.follow, name='follow'),
]

instapjt/instapjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instapjt/posts/urls.py
from django.urls import path
from . import views
# from django.conf import settings
# from django.conf.urls.static import static

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:post_pk>/comments', views.comments_create, name='comments_create'),
    path('<int:post_pk>/like', views.like, name='like'),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instapjt/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Document</title>
</head>
<body style="background-color: lightgray;">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #f5e6ab; position: sticky;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static './images/logo.png' %}" alt="" width="40" class="d-inline-block align-text-middle">
          Instagram
          </a>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:create' %}">New Post</a>
              </li>
            </ul>
          </div>
        </div>
        <div class=" d-flex mx-2">
          {% if user.is_authenticated %}
          <a href="{% url 'accounts:profile' user.pk %}" class=" btn btn-link text-decoration-none text-success text-nowrap me-3">{{ user.username }}</a>
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-danger" value="Logout">
          </form>
          {% else %}
          <a href="{% url 'accounts:login' %}">
            <button class="btn btn-outline-success btn-lg mx-1" type="submit">Login</button>
          </a>
          <a href="{% url 'accounts:signup' %}">
            <button class="btn btn-outline-info btn-lg mx-1" type="submit">Signup</button>
          </a>
          {% endif %}
        </div>
      </nav>
    <div>
      {% block content %}
      {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>