instapjt/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:pk>/profile/", views.profile, name="profile"),
    path('<int:pk>/follow', views.follow, name='follow'),
]

instapjt/instapjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instapjt/posts/urls.py
from django.urls import path
from . import views
# from django.conf import settings
# from django.conf.urls.static import static

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:post_pk>/comments', views.comments_create, name='comments_create'),
    path('<int:post_pk>/like', views.like, name='like'),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instapjt/posts/models.py
from django.db import models
from django.conf import settings 
# Create your models here.
class Post(models.Model):
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    image = models.ImageField(blank=True, upload_to="image/%Y/%m/%d")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

instapjt/posts/forms.py
from logging import PlaceHolder
from django import forms
from django import forms
from .models import Comment, Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ("content", "image")

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        exclude = ("post", "author")
    
    content = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                "class" : "d-inline",
                "placeholder" : "댓글을 입력해주세요.",
            },
        )
    )

instapjt/posts/views.py
import re
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_safe

from accounts.models import User
from .models import Post
from .forms import CommentForm, PostForm
# Create your views here.

@require_safe
def index(request):
    posts = Post.objects.order_by("created_at")
    comment_form = CommentForm()
    context = {
        "posts" : posts,
        "comment_form" : comment_form,
    }
    return render(request, "posts/index.html", context)

@login_required
@require_http_methods(["GET", "POST"])
def create(request):
    if request.method=="POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:index")
    else:
        form = PostForm()
    context = {
        'form' : form,
    }
    return render(request, "posts/create.html", context)

@login_required
@require_POST
def delete(request, pk):
    post = Post.objects.get(pk=pk)
    if request.user == post.author:
        post.delete()
    return redirect("posts:index")

@login_required
@require_http_methods(["POST", "GET"])
def update(request, pk):
    post = Post.objects.get(pk=pk)
    if request.user == post.author:
        if request.method == 'POST':
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                if request.FILES.get('image'):
                    post.image = request.FILES['image']
                post.save()
                return redirect("posts:index")
        else:
            form = PostForm(instance=post)

        context = {
            "form" : form,
            'post' : post,
        }
        return render(request, "posts/update.html", context)
    else:
        return redirect("posts:index")


@login_required
@require_POST
def comments_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    user = request.user
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = user
        comment.save()
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

@login_required
@require_POST
def like(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    user = request.user
    if post.like_users.filter(pk=user.pk).exists():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    return redirect("posts:index")

instapjt/posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
    <div class="d-flex flex-column mx-auto mt-5 bg-light border-radius p-3" style="width : 30%;">
        <h1>New Post</h1>
        <form action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="생성" class="btn btn-primary">
        </form>
    </div>
{% endblock content %}

instapjt/posts/templates/posts/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<h1 class="text-center">메인 화면</h1>
<hr>
<div class = "container d-flex flex-column mb-3 mx-auto mt-3 align-items-center">
    {% for post in posts %}
        <div class="card mb-5 " style="width:70%">
            <div class="card-header d-flex align-items-center">
                <div class="mx-1">
                    <img src="{{ post.author.profile_image.url }}" width="30px;" alt="profile image" data-bs-toggle="modal" data-bs-target="#profile-image{{ post.pk }}">
                </div>
                <!-- Modal -->
                <div class="modal" id="profile-image{{ post.pk }}" tabindex="-1" aria-labelledby="exampleModalToggle" aria-hidden="true">
                    <div class="modal-dialog" style="max-width : 50%;">
                        <div class="modal-content">
                            <div class="modal-body">
                                <img src="{{ post.author.profile_image.url }}" class="card-img-top" alt="image" style="max-height : 900px; object-fit : contain;">
                            </div>
                            <div class="modal-footer d-flex flex-column align-items-start">
                                <button type="button" class="d-block mx-auto btn btn-secondary" data-bs-dismiss="modal" style="width : 70%">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'accounts:profile' post.author.pk %}"class="h3 text-decoration-none text-info">{{ post.author }}</a>
            </div>
            {% if post.image %}
                <img src="{{ post.image.url }}" class="card-img-top" data-bs-toggle="modal" data-bs-target="#post{{ post.pk }}" alt="image" style="max-height:400px; object-fit : cover; object-position : left">              
                <!-- Modal -->
                <div class="modal" id="post{{ post.pk }}" tabindex="-1" aria-labelledby="exampleModalToggle" aria-hidden="true">
                    <div class="modal-dialog" style="max-width : 50%;">
                        <div class="modal-content">
                        <div class="modal-header">
                            <img src="{{ post.image.url }}" class="card-img-top" alt="image" style="max-height : 900px; object-fit : contain;">
                        </div>
                        <div class="modal-body">
                            {{ post.content }}
                        </div>
                        <div class="modal-footer d-flex flex-column align-items-start">
                            <ul class="mb-3">
                                {% for comment in post.comment_set.all %}
                                    <li>{{comment.author}} - {{ comment.content }}</li>
                                {% endfor %}
                            </ul> 
                            <form action="{% url 'posts:comments_create' post.pk %}" method="POST" class="container w-100 form-horizontal form-inline">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-9 form-group">
                                        {% bootstrap_form comment_form %}
                                    </div>
                                    <div class="col-3">
                                        <input type="submit" value="제출" class="btn btn-primary w-100">
                                    </div>
                                </div>
                            </form>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="width : 70%">Close</button>
                        </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="card-body" style="background-color : aquamarine;">
                <p class="mb-2">{{ post.content }}</p>
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row">
                        <form action="{% url 'posts:like' post.pk %}" method="POST" class="d-inlineblock me-2" style="min-width : 65px">
                            {% csrf_token %}
                            {% if user in post.like_users.all %}
                            <input type="submit" value="좋아요취소" class="btn btn-danger btn-sm">
                            {% else %}
                            <input type="submit" value="좋아요" class="btn btn-success btn-sm">
                            {% endif %}
                        </form>
                        <p data-bs-toggle="modal" data-bs-target="#post{{ post.pk }}" class="mb-0">댓글 {{ post.comment_set.count }}개</p>
                    </div>
                    {% if user == post.author %}
                        <div class="d-flex">
                            <a href="{% url 'posts:update' post.pk %}" class="btn btn-sm btn-info mx-1" style="width : 65px;  white-space: nowrap; box-sizing: border-box;">Edit</a>
                            <form action="{% url 'posts:delete' post.pk %}" method="POST" class="d-inline mx-1" style="width : 65px; white-space: nowrap; box-sizing: border-box;">
                                {% csrf_token %}
                                <input type="submit" value="DELETE" class="btn btn-danger btn-sm">
                            </form>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

instapjt/posts/templates/posts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
    <form action="{% url 'posts:update' post.pk %}" method="post" enctype="multipart/form-data" class="mx-auto my-5 w-50">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="수정" class="btn btn-success d-block">
    </form>

</div>
{% endblock content %}