instapjt/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:pk>/profile/", views.profile, name="profile"),
    path('<int:pk>/follow', views.follow, name='follow'),
]

instapjt/instapjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instapjt/posts/urls.py
from django.urls import path
from . import views
# from django.conf import settings
# from django.conf.urls.static import static

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:post_pk>/comments', views.comments_create, name='comments_create'),
    path('<int:post_pk>/like', views.like, name='like'),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instapjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

PROFILE_PATH = "profile_images"

def profile_image_path(instance, filename): # 반드시 이 2개의 변수 사용
    return f'{PROFILE_PATH}/{instance.username}/{filename}'

class User(AbstractUser):
    profile_image = models.ImageField(default=f"{PROFILE_PATH}/default_profile.png", upload_to=profile_image_path)
    followings = models.ManyToManyField("self", symmetrical=False, related_name="followers")
    about = models.TextField(max_length=200, blank=True)

instapjt/posts/models.py
from django.db import models
from django.conf import settings 
# Create your models here.
class Post(models.Model):
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    image = models.ImageField(blank=True, upload_to="image/%Y/%m/%d")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

instapjt/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.forms import TextInput

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ( 'profile_image', 'about', 'username')

    profile_image = forms.ImageField(
        label = "프로필 사진",
        required= False,
    )
    about = forms.CharField(
        label = "About",
        widget= forms.Textarea(
            attrs= {
                'placeholder' : '본인을 소개해주세요.',
                'row' :  3,
                'col' : 30,
            }
        )
    )

class CustomUserChangeForm(UserChangeForm):

    profile_image = forms.ImageField(
        label = "프로필 사진",
        required= False,
    )

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'profile_image', 'about',)
        # fields = ('email', 'first_name', 'last_name', 'profile_image')

instapjt/accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout

from accounts.models import User
from posts.forms import CommentForm
from posts.models import Post
from .forms import CustomUserCreationForm, CustomUserChangeForm
# Create your views here.

@require_http_methods(['POST', 'GET'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("posts:index")
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, "accounts/login.html", context)

@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            if request.FILES.get("profile_image"):
                user.profile_image = request.FILES.get("profile_image")
            user.save()
            auth_login(request, user)
            return redirect("posts:index")
    else:
        form = CustomUserCreationForm()
    
    context = {
        'form' : form,
    }
    return render(request, "accounts/signup.html", context)

@login_required
@require_POST
def logout(request):
    auth_logout(request)
    return redirect("accounts:login")

@login_required
@require_http_methods(["POST", "GET"])
def update(request):
    if request.method == "POST":
        print(request)
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            user = form.save()
            if request.FILES.get('profile_image'):
                user.profile_image = request.FILES.get('profile_image')
            user.save()
            return redirect("accounts:profile", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form" : form,
    }
    return render(request, "accounts/update.html", context)

@require_safe
def profile(request, pk):
    user = User.objects.get(pk=pk)
    posts = Post.objects.filter(author=user).order_by("created_at")
    comment_form = CommentForm()
    context = {
        "targetUser" : user,
        "posts" : posts,
        "comment_form" : comment_form,
    }
    return render(request, "accounts/profile.html", context)

@login_required
@require_POST
def follow(request, pk):
    you = User.objects.get(pk=pk)
    me = request.user
    if you.followers.filter(pk=me.pk).exists():
         you.followers.remove(me)
    else:
        you.followers.add(me)
    return redirect("accounts:profile", you.pk) 

instapjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="d-flex flex-column align-items-center mt-5 mx-auto" style="width: 50%">
    <h1>LOGIN</h1>
    <form action="{% url 'accounts:login' %}" method="post" class = "d-flex flex-column" style="width: 50%;">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="로그인" class="btn btn-success mt-3">
    </form>
</div>

{% endblock content %}

instapjt/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-12 col-xl-9">
          <div class="card">
            <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
              <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px; height: 150px;">
                <div style="width: 150px; height: 150px;">
                  <img src="{{ targetUser.profile_image.url }}"
                    alt="profile image" class="img-fluid img-thumbnail"
                    style="width: 150px; height: 150px; z-index: 1; object-fit : cover;" 
                    data-bs-toggle="modal" data-bs-target="#profile-image{{ targetUser.pk }}">
                  </div>
                <!-- Modal -->
                <div class="modal" id="profile-image{{ targetUser.pk }}" tabindex="-1" aria-labelledby="exampleModalToggle" aria-hidden="true">
                  <div class="modal-dialog" style="max-width : 50%;">
                      <div class="modal-content">
                          <div class="modal-body">
                              <img src="{{ targetUser.profile_image.url }}" class="card-img-top" alt="image" style="max-height : 900px; object-fit : contain;">
                          </div>
                          <div class="modal-footer d-flex flex-column align-items-start">
                              <button type="button" class="d-block mx-auto btn btn-secondary" data-bs-dismiss="modal" style="width : 70%">Close</button>
                          </div>
                      </div>
                  </div>
                </div>
                {% if targetUser == request.user %}
                  <a href="{% url 'accounts:update' %}" class="text-decoration-none">
                    <button type="button" class="btn btn-outline-dark" data-mdb-ripple-color="dark"
                    style="z-index: 1;">
                    Edit profile
                  </a>
                {% endif %}
                </button>
              </div>
              <div class="ms-3" style="margin-top: 150px;">
                <h5>{{ targetUser.username }}</h5>
              </div>
            </div>
            <div class="p-4 text-black" style="background-color: #f8f9fa;">
              <div class="d-flex justify-content-end text-center py-1">
                {% if targetUser != request.user %}
                  <div class="px-2">
                    <form action="{% url 'accounts:follow' targetUser.pk %}" method="post">
                      {% csrf_token %}
                      {% if targetUser in request.user.followings.all %}
                        <input type="submit" class="btn btn-danger" value="Unfollow">
                      {% else %}
                        <input type="submit" class="btn btn-success" value="Follow">
                      {% endif %}
                    </form>
                  </div>
                {% endif %}
                <div class="px-2">
                  <p class="mb-1 h5">{{ targetUser.post_set.count}}</p>
                  <p class="small text-muted mb-0">Posts</p>
                </div>
                <div class="px-2">
                  <p class="mb-1 h5">{{ targetUser.followers.count }}</p>
                  <p class="small text-muted mb-0">Followers</p>
                </div>
                <div class="px-2">
                  <p class="mb-1 h5">{{ targetUser.followings.count }}</p>
                  <p class="small text-muted mb-0">Following</p>
                </div>
              </div>
            </div>
            <div class="card-body p-4 text-black">
              <div class="mb-5">
                <p class="lead fw-normal mb-1">About</p>
                <div class="p-4" style="background-color: #f8f9fa;">
                  <pre class="my-auto">{{ targetUser.about }}</pre>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-center mb-4">
                <p class="lead fw-normal mb-0">Recent posts</p>
                <p class="mb-0"><a href="#!" class="text-muted">Show all</a></p>
              </div>
              <div class = "container d-flex flex-column mb-3 mx-auto mt-3 align-items-center">
                {% for post in posts %}
                    <div class="card mb-5 " style="width:70%">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="card-img-top" data-bs-toggle="modal" data-bs-target="#post{{ post.pk }}" alt="image" style="max-height:400px; object-fit : cover; object-position : left">              
                            <!-- Modal -->
                            <div class="modal" id="post{{ post.pk }}" tabindex="-1" aria-labelledby="exampleModalToggle" aria-hidden="true">
                                <div class="modal-dialog" style="max-width : 50%;">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                        <img src="{{ post.image.url }}" class="card-img-top" alt="image" style="max-height : 900px; object-fit : contain;">
                                    </div>
                                    <div class="modal-body">
                                        {{ post.content }}
                                    </div>
                                    <div class="modal-footer d-flex flex-column align-items-start">
                                        <ul class="mb-3">
                                            {% for comment in post.comment_set.all %}
                                                <li>{{comment.author}} - {{ comment.content }}</li>
                                            {% endfor %}
                                        </ul> 
                                        <form action="{% url 'posts:comments_create' post.pk %}" method="POST" class="container w-100 form-horizontal form-inline">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-9 form-group">
                                                    {% bootstrap_form comment_form %}
                                                </div>
                                                <div class="col-3">
                                                    <input type="submit" value="제출" class="btn btn-primary w-100">
                                                </div>
                                            </div>
                                        </form>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="width : 70%">Close</button>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                        <div class="card-body" style="background-color : aquamarine;">
                            <p class="mb-2">{{ post.content }}</p>
                            <div class="d-flex justify-content-between">
                                <div class="d-flex flex-row">
                                    <form action="{% url 'posts:like' post.pk %}" method="POST" class="d-inlineblock me-2" style="min-width : 65px">
                                        {% csrf_token %}
                                        {% if user in post.like_users.all %}
                                        <input type="submit" value="좋아요취소" class="btn btn-danger btn-sm">
                                        {% else %}
                                        <input type="submit" value="좋아요" class="btn btn-success btn-sm">
                                        {% endif %}
                                    </form>
                                    <p data-bs-toggle="modal" data-bs-target="#post{{ post.pk }}" class="mb-0">댓글 {{ post.comment_set.count }}개</p>
                                </div>
                                {% if user == post.author %}
                                    <div class="d-flex">
                                        <a href="{% url 'posts:update' post.pk %}" class="btn btn-sm btn-info mx-1" style="width : 65px;  white-space: nowrap; box-sizing: border-box;">Edit</a>
                                        <form action="{% url 'posts:delete' post.pk %}" method="POST" class="d-inline mx-1" style="width : 65px; white-space: nowrap; box-sizing: border-box;">
                                            {% csrf_token %}
                                            <input type="submit" value="DELETE" class="btn btn-danger btn-sm">
                                        </form>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

instapjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="d-flex flex-column align-items-center mt-5 mx-auto" style="width: 50%">
    <h1>SIGNUP</h1>
    <form action="{% url 'accounts:signup' %}" method="post" class = "d-flex flex-column" style="width: 50%;" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="회원가입" class="btn btn-success mt-3">
    </form>
</div>

{% endblock content %}

instapjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="d-flex flex-column align-items-center mt-5 mx-auto" style="width: 50%">
    <h1>UPDATE</h1>
    <form action="{% url 'accounts:update' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="수정" class="btn btn-info mt-3">
        </form>
    </div>
{% endblock content %}